### ISSUE TITLE
Paris

### ISSUE THREAD

**Issue by rubyFeedback** [Austin-BG/HTaM#11]
I just read this thread here:

https://forums.beamdog.com/discussion/81464/mod-heroes-thieves-and-moneylenders-banter-quest-romance-mod-for-bg2/p8

Sjerrie wrote:

> Paris still doesn't show up, spawning him in with the console makes him unresponsive, as does manually advancing the value.

> This'll be the last time I install so many quest mods, it always borks at least one

I did not know Paris was part of the mod here, but I also have tons of issues with Paris. I think this is in part because of other mods creating problems, in particular in the graveyard district. The reason I think is the case is because the Paris situation keeps on resolving differently (in erratic ways) and I changed installation order of mods to try to see if some other problems go away.

For instance, Paris would say he meets me at the graveyard, but never shows up.

Or, he shows up, but never says anything.

Or, he shows up eventually, and does not say anything, but then suddenly the quest is triggered when ANOTHER quest is
running in the graveyard, which leads to funny overlap-like situations.

HTaM has great ideas, I finally found the bank too (back when I said I could not find it, it did not seem to be installed), but if I do not go there for the first time, then there is, oddly enough, no way to enter the circus in the middle of the map. Only when I first visit the bank, will there be an entry to the circus. So the mod has many minor problems IMO.

In my latest run a few weeks ago, I think I accidentally clicked on the russian translations, which meant I got tons of russian symbols (this is not so much the fault of HTaM and perhaps more of that manual installation way; I also have to say I hate weidu, that tool really should have been eliminated years ago already, it is sooooo bad ... I wonder how people can work with it).

Anyway, I hope this is not too discouraging. I think the mod is great overall, but the small issues means I'll skip it, in order to avoid other problems. Also note I think one component installs a raid against the bank, and there were a few bugs too, but I only played it through once.

**Comment by Austin-BG** [comment]
Hello! If you are using the latest version of the mod (4.3.1), then changes have been made to the Paris quest scripts and there should be no more problems. At least after this update my tests did not reveal a single problem. But if possible, I will check this quest again, thanks for the information.
Do not forget that Paris appears in the Graveyard area (after talking with him in the Government area) only at night and at the southern entrance to the location and he must see the player in order to speak. 

Regarding the entrance to the circus on the Promenade, this is not related to the HtaM mod, since this entry point is not affected anywhere in it, and the entrance to the bank is added in a completely different place, in the southern part of the map. This problem is caused by some other mod or compatibility issues in a large selection of mods.

**Comment by Austin-BG** [comment]
Sorry, but I don’t quite understand what you mean here and what specific bugs are we talking about here: _“one component installs a raid against the bank”_

**Comment by Austin-BG** [comment]
Hello! The mod has been updated to version 4.3.2! Among other changes, the code has been reworked to eliminate bugs with Lord Paris! Now there should be no problems, I reworked the entire system of variables in this quest and checked several times, Paris appears as it should. Thank you!
